package com.usaparel.model.AM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 07 10:39:07 PKT 2017
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    int getScannedPacks(int packingID);


    int adjustQuantity(int newShipID, int newPackingID, int newStatus, int newPackingQty, int newQuantity);

    int initialStatus(int pid, int s);

    int challanExists(int challan_id);
}

