package com.usaparel.model.VO.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 21 15:03:14 PKT 2017
// ---------------------------------------------------------------------
public interface VOCustScannedHeaderRow extends Row {
    void scanComplete(String challan_id);
}

